from flask import Flask, render_template, request, redirect, session, send_file
import sqlite3
import os
import re
import docx
import pdfplumber
from groq import Groq
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

app = Flask(__name__)
app.secret_key = "qbank_secret_key"
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024

try:
    groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
except:
    groq_client = None

DATABASE = 'qbank_app.db'

def get_db():
    conn = sqlite3.connect(DATABASE)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)')
    cursor.execute('CREATE TABLE IF NOT EXISTS subjects (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, name TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id))')
    cursor.execute('CREATE TABLE IF NOT EXISTS questions (id INTEGER PRIMARY KEY AUTOINCREMENT, subject_id INTEGER NOT NULL, question_text TEXT NOT NULL, marks INTEGER, unit TEXT, FOREIGN KEY (subject_id) REFERENCES subjects(id))')
    cursor.execute('CREATE TABLE IF NOT EXISTS note_chunks (id INTEGER PRIMARY KEY AUTOINCREMENT, subject_id INTEGER NOT NULL, source_file TEXT, chunk_text TEXT NOT NULL, FOREIGN KEY (subject_id) REFERENCES subjects(id))')
    cursor.execute('CREATE TABLE IF NOT EXISTS answers (id INTEGER PRIMARY KEY AUTOINCREMENT, question_id INTEGER NOT NULL, answer_text TEXT, word_count INTEGER, FOREIGN KEY (question_id) REFERENCES questions(id))')
    conn.commit()
    conn.close()

init_db()

def parse_questions(docx_paths):
    questions = []
    seen = set()
    skip_keywords = ['subject name', 'subject code', 'question bank', 'department', 'semester', 'module', 'unit', 'section', 'part a', 'part b', 'sl no', 'sl.no', 'course code', 'course name', 'faculty', 'year', 'batch', 'college', 'ia1', 'ia2', 'ia3', 'internal assessment']
    
    for docx_path in docx_paths:
        doc = docx.Document(docx_path)
        for para in doc.paragraphs:
            text = para.text.strip()
            if not text or len(text) < 15 or text in seen or any(kw in text.lower() for kw in skip_keywords) or len(text.split()) < 5:
                continue
            seen.add(text)
            match = re.search(r'\b(\d+)\s*[Mm]arks?\b|\[(\d+)\]|\((\d+)\)|\b(\d+)[Mm]\b', text)
            marks = int(next((m for m in match.groups() if m), 0)) if match else 0
            questions.append({"text": text, "marks": marks})
        
        for table in doc.tables:
            for row in table.rows:
                for cell in row.cells:
                    text = cell.text.strip()
                    if not text or len(text) < 15 or text in seen or any(kw in text.lower() for kw in skip_keywords) or len(text.split()) < 5:
                        continue
                    seen.add(text)
                    match = re.search(r'\b(\d+)\s*[Mm]arks?\b|\[(\d+)\]|\((\d+)\)|\b(\d+)[Mm]\b', text)
                    marks = int(next((m for m in match.groups() if m), 0)) if match else 0
                    questions.append({"text": text, "marks": marks})
    return questions

def parse_notes(pdf_paths):
    all_text = ""
    for pdf_path in pdf_paths:
        try:
            with pdfplumber.open(pdf_path) as pdf:
                for page in pdf.pages:
                    text = page.extract_text()
                    if text:
                        all_text += text + "\n\n"
        except:
            pass
    return all_text

def generate_one_answer(question, notes_text):
    marks = question["marks"] if question["marks"] > 0 else 10
    return f"<strong>Sample Answer ({marks} marks):</strong><br>This is a test answer generated by the system."

def generate_all_answers(questions, notes_text):
    return [generate_one_answer(q, notes_text) for q in questions]

def generate_pdf(questions, answers, output_path, subject_name):
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph(f"{subject_name} - Answers", styles['Title']))
    story.append(Spacer(1, 20))
    for i, (q, a) in enumerate(zip(questions, answers)):
        marks = q['marks'] if q['marks'] > 0 else 10
        q_text = f"Q{i+1} ({marks} marks): {q['text']}"
        story.append(Paragraph(q_text, styles['Heading3']))
        story.append(Spacer(1, 6))
        clean = re.sub(r'<.*?>', '', a)
        story.append(Paragraph(clean, styles['Normal']))
        story.append(Spacer(1, 20))
    doc.build(story)

@app.route("/")
def home():
    return redirect("/login") if "user_id" not in session else redirect("/dashboard")

@app.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        db = get_db()
        cursor = db.cursor()
        try:
            cursor.execute("INSERT INTO users (email, password_hash) VALUES (?, ?)", (email, password))
            db.commit()
            return redirect("/login")
        except:
            return "Email already exists."
        finally:
            db.close()
    return render_template("signup.html")

@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        db = get_db()
        cursor = db.cursor()
        cursor.execute("SELECT id FROM users WHERE email=? AND password_hash=?", (email, password))
        user = cursor.fetchone()
        db.close()
        if user:
            session["user_id"] = user[0]
            return redirect("/dashboard")
        return "Invalid credentials."
    return render_template("login.html")

@app.route("/logout")
def logout():
    session.clear()
    return redirect("/login")

@app.route("/dashboard")
def dashboard():
    if "user_id" not in session:
        return redirect("/login")
    db = get_db()
    cursor = db.cursor()
    cursor.execute("SELECT id, name FROM subjects WHERE user_id=?", (session["user_id"],))
    subjects = cursor.fetchall()
    db.close()
    return render_template("dashboard.html", subjects=subjects)

@app.route("/add_subject", methods=["GET", "POST"])
def add_subject():
    if "user_id" not in session:
        return redirect("/login")
    if request.method == "POST":
        name = request.form["name"]
        db = get_db()
        cursor = db.cursor()
        cursor.execute("INSERT INTO subjects (user_id, name) VALUES (?, ?)", (session["user_id"], name))
        db.commit()
        db.close()
        return redirect("/dashboard")
    return render_template("add_subject.html")

@app.route("/subject/<int:subject_id>")
def subject_detail(subject_id):
    if "user_id" not in session:
        return redirect("/login")
    db = get_db()
    cursor = db.cursor()
    cursor.execute("SELECT id, name FROM subjects WHERE id=? AND user_id=?", (subject_id, session["user_id"]))
    subject = cursor.fetchone()
    cursor.execute("SELECT q.question_text, q.marks, a.answer_text FROM questions q LEFT JOIN answers a ON q.id = a.question_id WHERE q.subject_id=?", (subject_id,))
    qa_pairs = cursor.fetchall()
    db.close()
    return render_template("subject.html", subject=subject, qa_pairs=qa_pairs) if subject else "Not found"

@app.route("/upload/<int:subject_id>", methods=["GET", "POST"])
def upload(subject_id):
    if "user_id" not in session:
        return redirect("/login")
    if request.method == "POST":
        qbank_files = request.files.getlist("qbank")
        notes_files = request.files.getlist("notes")
        upload_folder = f"uploads/{subject_id}"
        os.makedirs(upload_folder, exist_ok=True)
        
        qbank_paths = []
        for i, f in enumerate(qbank_files):
            if f and f.filename:
                path = os.path.join(upload_folder, f"qbank_{i}.docx")
                f.save(path)
                qbank_paths.append(path)
        
        notes_paths = []
        for i, f in enumerate(notes_files):
            if f and f.filename:
                path = os.path.join(upload_folder, f"notes_{i}.pdf")
                f.save(path)
                notes_paths.append(path)
        
        questions = parse_questions(qbank_paths)
        notes_text = parse_notes(notes_paths)
        
        db = get_db()
        cursor = db.cursor()
        cursor.execute("DELETE FROM answers WHERE question_id IN (SELECT id FROM questions WHERE subject_id=?)", (subject_id,))
        cursor.execute("DELETE FROM questions WHERE subject_id=?", (subject_id,))
        cursor.execute("DELETE FROM note_chunks WHERE subject_id=?", (subject_id,))
        db.commit()
        
        answers = generate_all_answers(questions, notes_text)
        
        for question, answer in zip(questions, answers):
            cursor.execute("INSERT INTO questions (subject_id, question_text, marks) VALUES (?, ?, ?)", (subject_id, question["text"], question["marks"]))
            question_id = cursor.lastrowid
            cursor.execute("INSERT INTO answers (question_id, answer_text, word_count) VALUES (?, ?, ?)", (question_id, answer, len(answer.split())))
        db.commit()
        db.close()
        return redirect(f"/subject/{subject_id}")
    
    return render_template("upload.html", subject_id=subject_id)

@app.route("/download/<int:subject_id>")
def download(subject_id):
    if "user_id" not in session:
        return redirect("/login")
    db = get_db()
    cursor = db.cursor()
    cursor.execute("SELECT q.question_text, q.marks, a.answer_text FROM questions q LEFT JOIN answers a ON q.id = a.question_id WHERE q.subject_id=?", (subject_id,))
    rows = cursor.fetchall()
    cursor.execute("SELECT name FROM subjects WHERE id=?", (subject_id,))
    subject = cursor.fetchone()
    db.close()
    
    questions = [{"text": r[0], "marks": r[1]} for r in rows]
    answers = [r[2] or "" for r in rows]
    
    output_folder = f"outputs/{subject_id}"
    os.makedirs(output_folder, exist_ok=True)
    output_path = os.path.join(output_folder, "answers.pdf")
    
    generate_pdf(questions, answers, output_path, subject[0])
    return send_file(output_path, as_attachment=True, download_name=f"{subject[0]}_answers.pdf")

if __name__ == "__main__":
    app.run(debug=True)
